version: 2
jobs:
  build:
    docker:
      - image: circleci/python

    steps:
      - checkout
      
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && apt-get install -y cmake'

      - run:
          command: gcc --version

      - run:
          name: Set up MLIR.
          command: |
            git clone https://github.com/llvm/llvm-project.git  
            git clone https://github.com/tensorflow/mlir llvm-project/llvm/projects/mlir 
            mkdir llvm-project/build 
            cd llvm-project/build 
            cmake -G Ninja ../llvm -DLLVM_ENABLE_RTTI=ON  -DLLVM_BUILD_EXAMPLES=OFF -DLLVM_TARGETS_TO_BUILD="host" 
            cmake --build . --target check-mlir

      - run:
          name: Print the Current Time
          command: date
